name: Sync Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  #   pull_request:
  #     branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest

    steps:
      - name: Cancel if reach condition
        if: ${{ github.event_name == 'update readme'}}
        uses: andymckay/cancel-action@0.2

      - name: Setup Env
        run: |
          # choco upgrade git -y
          git config --global init.defaultbranch main

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      # - name: Collect Info
      #   run: |
      #     $hash=(git log -1 --format='%h')
      #     $title=(git log -1 --format='%s')
      #     $title_tag=(git log -1 --format='%f')
      #     $body=(git log -1 --format='%b')
      #     echo title="$title" >> "$GITHUB_ENV"
      #     echo title_tag="$title_tag" >> "$GITHUB_ENV"

      #     if($title -eq "update readme"){exit 1}

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          path: coredns
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: qzlin/forward
          path: forward
          persist-credentials: false
          fetch-depth: 0
      - name: Get git-filter-repo
        run: Invoke-WebRequest https://github.com/newren/git-filter-repo/raw/main/git-filter-repo -OutFile git-filter-repo.py

      - name: Set Git Info & Check Git config
        run: |
          git config --global user.email "qzlin01@163.com"
          git config --global user.name "QZLin"
          git config --global --unset core.repositoryformatversion
          git config --list

      - name: Extract forward and split history
        run: . ./actions.ps1

      - name: Setup repo ssh key
        run: |
          New-Item -ItemType Directory ~/.ssh -ErrorAction SilentlyContinue
          New-Item ~/.ssh/bot_id
          python binary_tool.py -d --base64-input ${{ secrets.BOT_SSH_DEPLOY_PRIVATE_KEY }} -o (Get-Item ~/.ssh/bot_id)
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # $key="${{ secrets.BOT_SSH_DEPLOY_PRIVATE_KEY }}"
          # $key | Set-Content -NoNewline -Path ~/.ssh/bot_id
          # Write-Output "${{ secrets.BOT_ID_RSA }}" > ~/.ssh/id_rsa
          # Write-Output "${{ secrets.BOT_ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
      - name: Pull and push
        run: |
          Push-Location coredns
          git config core.sshCommand "ssh -i ~/.ssh/bot_id"
          Get-Item "~/.ssh/bot_id"
          Get-Command ssh

          git config --list
          git config --list --local

          git branch -M main
          git push --set-upstream git@github.com:QZLin/forward.git main --force
          # git push --set-upstream https://oauth2:${{ secrets.TOKEN }}@github.com/QZLin/forward main --force
          Pop-Location
      - name: Update Readme
        run: |
          New-Item -ItemType Directory ~/.ssh -ErrorAction SilentlyContinue
          New-Item ~/.ssh/self_id
          python binary_tool.py -d --base64-input ${{ secrets.BOT_SSH_DEPLOY_SELF_PRIVATE_KEY }} -o (Get-Item ~/.ssh/self_id)
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config core.sshCommand "ssh -i ~/.ssh/self_id"
          . ./update_readme.ps1
        # env:
        #   TOKEN: ${{ secrets.TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: debug-artifact
          path: forward
