name: Sync Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  #   pull_request:
  #     branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest

    steps:
      - name: Setup Env
        run: |
          # choco upgrade git -y
          git config --global init.defaultbranch main

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          path: coredns
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          repository: qzlin/forward
          path: forward
          persist-credentials: false
          fetch-depth: 0
      - name: Get git-filter-repo
        run: Invoke-WebRequest https://github.com/newren/git-filter-repo/raw/main/git-filter-repo -OutFile git-filter-repo.py

      - name: Set Git Info
        run: |
          git config --global user.email "qzlin01@163.com"
          git config --global user.name "QZLin"

      - name: Check Git config
        run: |
          git config --global --unset core.repositoryformatversion
          git config --list

      - name: Extract forward and split history
        run: . ./actions.ps1

      # - name: Setup ssh key
      #   run: |
      #     New-Item -ItemType Directory ~/.ssh -ErrorAction SilentlyContinue
      #     Write-Output "${{ secrets.BOT_ID_RSA }}" > ~/.ssh/id_rsa
      #     Write-Output "${{ secrets.BOT_ID_RSA_PUB }}" > ~/.ssh/id_rsa.pub
      - name: Pull and push
        run: |
          Push-Location coredns
          git branch -M main
          git push --set-upstream https://oauth2:${{ secrets.TOKEN }}@github.com/QZLin/forward main --force
          Pop-Location
        # env:
        #   TOKEN: ${{ secrets.TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: debug-artifact
          path: forward
