name: Sync Repo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Extract forward and split history
        run: . actions.ps1
      - name: Commit and push
        run: |
          Push-Location forward
          git config --global user.email "qzlin01@163.com"
          git config --global user.name "QZLin"

          git branch main
          git switch main
          git remote add origin https://${{ secrets.TOKEN }}@github.com/QZLin/forward.git

          git push --set-upstream origin main --force
          Pop-Location

      - uses: actions/upload-artifact@v2
        with:
          name: debug-artifact
          path: forward